version: "3"
services:
    coexya-mantis-devops-bridge:
        container_name: "coexya-mantis-devops-bridge"
        image: elyspio/mantis-devops-bridge
        volumes:
            - "./config/back/appsettings.docker.json:/back/appsettings.docker.json"
        networks:
            - external
            - internal
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.coexya-mantis-devops-bridge-prefix.stripprefix.prefixes=/coexya-mantis-devops-bridge"
            - "traefik.http.routers.coexya-mantis-devops-bridge.middlewares=coexya-mantis-devops-bridge-prefix@docker"
            - "traefik.http.routers.coexya-mantis-devops-bridge.rule=PathPrefix(`/coexya-mantis-devops-bridge`)"
            - "traefik.http.services.coexya-mantis-devops-bridge.loadbalancer.server.port=4000"
            - "traefik.http.routers.coexya-mantis-devops-bridge.entrypoints=external"



networks:
    internal:
        external: true
    external:
        external: true
